* My Dotfiles
  Planning my dotfile repo. My current YADR/Prezto setup is far too slow. I want
  `startup` and `ls` to be instant.
** OSX defaults
*** Defaults
**** animations:
     #+begin_src shell

     # opening and closing windows and popovers
     defaults write -g NSAutomaticWindowAnimationsEnabled -bool false

     # smooth scrolling
     defaults write -g NSScrollAnimationEnabled -bool false

     # showing and hiding sheets, resizing preference windows, zooming windows
     # float 0 doesn't work
     defaults write -g NSWindowResizeTime -float 0.001

     # opening and closing Quick Look windows
     defaults write -g QLPanelAnimationDuration -float 0

     # rubberband scrolling (doesn't affect web views)
     defaults write -g NSScrollViewRubberbanding -bool false

     # resizing windows before and after showing the version browser
     # also disabled by NSWindowResizeTime -float 0.001
     defaults write -g NSDocumentRevisionsWindowTransformAnimation -bool false

     # showing a toolbar or menu bar in full screen
     defaults write -g NSToolbarFullScreenAnimationDuration -float 0

     # scrolling column views
     defaults write -g NSBrowserColumnAnimationSpeedMultiplier -float 0

     # showing the Dock
     defaults write com.apple.dock autohide-time-modifier -float 0
     defaults write com.apple.dock autohide-delay -float 0

     # showing and hiding Mission Control, command+numbers
     defaults write com.apple.dock expose-animation-duration -float 0

     # showing and hiding Launchpad
     defaults write com.apple.dock springboard-show-duration -float 0
     defaults write com.apple.dock springboard-hide-duration -float 0

     # changing pages in Launchpad
     defaults write com.apple.dock springboard-page-duration -float 0

     # at least AnimateInfoPanes
     defaults write com.apple.finder DisableAllAnimations -bool true

     # sending messages and opening windows for replies
     defaults write com.apple.Mail DisableSendAnimations -bool true
     defaults write com.apple.Mail DisableReplyAnimations -bool true
     #+end_src
** Issues
*** `ls` is slow. No matter the directory, there's always a delay compared to default zsh.
**** has something to do with fasd.
     I renamed fasd.zsh in .zsh.after/ to fasd.backup so that it's ignored for
     now. The only configs in that file are aliases and something for the fasd
     cache, so it must have something to do with the cache. Also replaced the fasd_cd function with the z script, which is a fine
     workaround for now.
** Requirements
*** brew
*** ruby
** dotfiles
*** .nvimrc
    A very basic one, cause I'm mostly using Spacemacs.
*** .zshrc
    Using zsh obviously. Instead of installing a zsh framework, I'll install a
    simple zsh package manager like zgen. Research and find the best lightweight
    one.
**** zgen
**** antigen
*** .tmux.conf
*** .spacemacs
*** .config/.nvim/init.vim
*** .aliases
** Install Script
   Will probably write this in Ruby. Just because I'm more experienced with it
   than Perl/Python/Bash/Zsh.
*** ./install.rb

















* TODO Link other dotfiles
** link .zshrc
** link .spacemacs
** link .tmux.conf
   should probably make a tmux directory, and link that instead.
*** link .tmux.theme
** link user conf file
*** ~/.aliases.user.zsh
*** ~/.tmux.conf.user
